2025/04/20 02:47:38 [emerg] 1#1: unknown directive "lua_package_path" in /etc/nginx/nginx.conf:8
2025/04/20 02:47:40 [emerg] 1#1: unknown directive "lua_package_path" in /etc/nginx/nginx.conf:8
2025/04/20 02:47:41 [emerg] 1#1: unknown directive "lua_package_path" in /etc/nginx/nginx.conf:8
2025/04/20 02:47:43 [emerg] 1#1: unknown directive "lua_package_path" in /etc/nginx/nginx.conf:8
2025/04/20 02:47:45 [emerg] 1#1: unknown directive "lua_package_path" in /etc/nginx/nginx.conf:8
2025/04/20 02:47:47 [emerg] 1#1: unknown directive "lua_package_path" in /etc/nginx/nginx.conf:8
2025/04/20 02:47:51 [emerg] 1#1: unknown directive "lua_package_path" in /etc/nginx/nginx.conf:8
2025/04/20 02:47:58 [emerg] 1#1: unknown directive "lua_package_path" in /etc/nginx/nginx.conf:8
2025/04/20 02:50:55 [error] 29#29: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.175.111.239, server: microservices.appf4.io.vn, request: "GET / HTTP/1.1", upstream: "http://172.18.0.5:8080/", host: "microservices.appf4.io.vn", referrer: "http://microservices.appf4.io.vn/"
2025/04/20 02:50:57 [error] 28#28: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 192.175.111.248, server: microservices.appf4.io.vn, request: "GET / HTTP/1.1", upstream: "http://172.18.0.5:8080/", host: "microservices.appf4.io.vn", referrer: "http://microservices.appf4.io.vn/"
2025/04/20 02:50:59 [error] 29#29: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 64.15.129.121, server: microservices.appf4.io.vn, request: "GET / HTTP/1.1", upstream: "http://172.18.0.5:8080/", host: "microservices.appf4.io.vn", referrer: "http://microservices.appf4.io.vn/"
2025/04/20 02:51:00 [error] 29#29: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 64.15.129.108, server: microservices.appf4.io.vn, request: "GET / HTTP/1.1", upstream: "http://172.18.0.5:8080/", host: "microservices.appf4.io.vn", referrer: "http://microservices.appf4.io.vn/"
